name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checktout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./ExpenseTrack.sln

      - name: Build
        run: dotnet build ./ExpenseTrack.sln --configutarion Release --no-restore

      - name: Publish
        run: dotnet publish ./ExpenseTrack.sln -- configuration Release --no-build
